stages:
  - build
  - test
  - publish

build job:
  stage: build
  tags: 
    - costas
  environment:
    name: staging
  script:
    - dotnet build

test job:
  stage: test
  variables:
    GIT_CLEAN_FLAGS: none
  tags:
    - costas
  environment:
    name: staging
  script:
    - dotnet test --no-build --logger "junit;LogFilePath=Report.xml"
  artifacts:
    paths:
      - ./tests/CC.CSX.Tests/Report.xml




