workflow:
  name: 'Pipeline for branch: $CI_COMMIT_BRANCH'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

on_branches:
  only:
    - branches
  script:
    - echo in test job


on_mr:
  only:
    - merge_requests
  script:
    - echo in build job