stages:
  - build
  - test
  - publish
build job:
  stage: build
  tags: 
    - costa-docker
  environment:
    name: staging
  script:
    - dotnet build --configuration Release
test job:
  stage: test
  variables:
    GIT_CLEAN_FLAGS: none
  tags:
    - costa-docker
  environment:
    name: staging
  script:
    - dotnet test --no-build --configuration Release --logger "junit;LogFilePath=Report.xml"
  artifacts:
    reports:
      junit: ./tests/CC.CSX.Tests/Report.xml
package job:
  stage: publish
  tags:
    - costa-docker

  script:
    - dotnet pack -o ./package
  artifacts:
    paths:
      - ./package/**/*

publish job:
  stage: publish
  script: 
    - export
  # script: dotnet nuget push src/CC.CSX/bin/Release/CC.CSX.0.1.5.nupkg --api-key ${NUGET_API_KEY} -s https://api.nuget.org/v3/index.json




