stages:
  - build
  - test
  - publish
build job:
  stage: build
  tags: 
    - costa-docker
  environment:
    name: staging
  script:
    - dotnet build --configuration Release
test job:
  stage: test
  variables:
    GIT_CLEAN_FLAGS: none
  tags:
    - costa-docker
  environment:
    name: staging
  script:
    - dotnet test --no-build --configuration Release --logger "junit;LogFilePath=Report.xml"
  artifacts:
    paths:
      - ./tests/CC.CSX.Tests/Report.xml
pack job:
  stage: publish
  tags:
    - costa-docker
  script:
    - dotnet pack -o ./package




