stages:
  - build
  - test
  - publish

build job:
  stage: build
  tags: 
    - costas
  environment:
    name: staging
  script:
    - dotnet build

test job:
  stage: test
  tags:
    - costas
  environment:
    name: staging
  script:
    - dotnet test



