stages:
  - build
  - test
  - publish

include:
  - local: 'ci/template.yml'
  - local: 'ci/combo.yml'
  - local: 'ci/build.yml'
  - local: 'ci/test.yml'
  - local: 'ci/package.yml'
  - local: 'ci/publish.yml'
