build:
  stage: build
  extends:
    - .base
    - .tags
    - .image
  script:
    - echo "Gjorgji"
    - !reference [.base, script]
    - echo "done"
    # - dotnet restore
    # - dotnet build --framework net8.0 --configuration Release src/CC.CSX/CC.CSX.csproj
