build-job:
  stage: build
  extends:
    - .base
    - .tags
    - .image
  variables: 
    GIT_CLEAN_FLAGS: none
  script:
    - echo $CI_COMMIT_BRANCH
    - dotnet restore --packages /packages
    - NUGET_PACKAGES=/packages && dotnet build --no-restore --configuration Release --output /builds_cache/$CI_COMMIT_BRANCH 
