build:
  stage: build
  extends:
    - .base
    - .tags
    - .image
  rules:
    - when: never
  script:
    - dotnet restore --packages /packages
    - dotnet build --framework net8.0 --no-restore --configuration Release --output /builds/$CI_BRANCH_NAME src/CC.CSX/CC.CSX.csproj
