build:
  stage: build
  extends:
    - .base
    - .tags
    - .image
  rules:
    - when: never
  script:
    - echo $CI_COMMIT_BRANCH
    - dotnet restore --packages /packages
    - NUGET_PACKAGES=/packages && dotnet buil: --no-restore --configuration Release --output /builds_cache/$CI_COMMIT_BRANCH 
