build:
  stage: build
  extends:
    - .base
    - .tags
    - .image
  rules:
    - when: never
  script:
    - dotnet restore
    - dotnet build --framework net8.0 --no-restore --configuration Release --output /dist/$CI_BRANCH_NAME src/CC.CSX/CC.CSX.csproj
