build:
  stage: build
  extends:
    - .base
    - .tags
    - .image
  script:
    - reference! [.base, script]

    # - dotnet restore
    # - dotnet build --framework net8.0 --configuration Release src/CC.CSX/CC.CSX.csproj
