build-job:
  stage: build
  extends:
    - .base
    - .tags
    - .image
  variables: 
    GIT_CLEAN_FLAGS: none
  script:
    - echo $CI_COMMIT_BRANCH
    # - dotnet restore --packages /packages
    - NUGET_PACKAGES=/packages && dotnet build --configuration Release --output /output/$CI_COMMIT_BRANCH --artifacts-path /artifacts/$CI_COMMIT_BRANCH 

