build:
  stage: build
  extends:
    - .base
    - .tags
    - .image
  rules:
    - when: never
  script:
    - echo $CI_COMMIT_BRANCH
    - dotnet restore --packages /packages
    - dotnet build \
      --framework net8.0 \
      --no-restore \
      --configuration Release \
      --output /builds/$CI_COMMIT_BRANCH \
      src/CC.CSX/CC.CSX.csproj
