name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  NUGET_SOURCE: "./dist/packages"
  NUGET_PUBLISH_SOURCE: "https://api.nuget.org/v3/index.json"
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Set version
      run: source eng/load_env.sh && echo VERSION=$VERSION >> $GITHUB_ENV
    - name: Bump Version
      run: source eng/load_env.sh && source eng/bump-version.sh
    - name: ENV Check
      run: echo "$GITHUB_CONTEXT"
    - name: Build all packages
      run: source eng/load_env.sh && source eng/github-build-all.sh
    - name: Test
      run: dotnet test -c Release
    - name: Package
      run: source eng/load_env.sh && source eng/package-all.sh
    - name: 'Upload Nuget packages'
      uses: actions/upload-artifact@v3
      with: 
        name: Nuget
        path: dist/packages/*.nupkg

